export const LOADING_SEARCHING = "LOADING_SEARCHING";
export const SUCCESS_SEARCHING = "SUCCESS_SEARCHING";
export const ERROR_SEARCHING = "ERROR_SEARCHING";

export const LOADING_USERDETAIL = "LOADING_USERDETAIL";
export const SUCCESS_USERDETAIL = "SUCCESS_USERDETAIL";
export const ERROR_USERDETAIL = "ERROR_USERDETAIL";
